"""Create all tables with improved schema

Revision ID: 4edab55ad5f6
Revises: 
Create Date: 2025-09-16 10:47:24.384051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edab55ad5f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'studentcount')
    op.drop_index(op.f('idx_scores_actual_gin'), table_name='scores', postgresql_using='gin')
    op.drop_index(op.f('idx_scores_predicted_gin'), table_name='scores', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scores_predicted_gin'), 'scores', ['predicted_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scores_actual_gin'), 'scores', ['actual_scores'], unique=False, postgresql_using='gin')
    op.add_column('grades', sa.Column('studentcount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
