"""add_applicable_parallels_to_subjects

Revision ID: 812064162958
Revises: a2c672f37bbf
Create Date: 2025-09-23 23:55:14.644435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '812064162958'
down_revision: Union[str, Sequence[str], None] = 'a2c672f37bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed problematic column drops that don't exist
    op.drop_index(op.f('idx_scores_actual_gin'), table_name='scores', postgresql_using='gin')
    op.drop_index(op.f('idx_scores_predicted_gin'), table_name='scores', postgresql_using='gin')
    op.add_column('subjects', sa.Column('applicable_parallels', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'applicable_parallels')
    op.create_index(op.f('idx_scores_predicted_gin'), 'scores', ['predicted_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scores_actual_gin'), 'scores', ['actual_scores'], unique=False, postgresql_using='gin')
    # Removed problematic column additions that don't exist
    # ### end Alembic commands ###
