"""add_applicable_parallels_to_subjects

Revision ID: 812064162958
Revises: a2c672f37bbf
Create Date: 2025-09-23 23:55:14.644435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '812064162958'
down_revision: Union[str, Sequence[str], None] = 'a2c672f37bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the applicable_parallels column, skip problematic operations
    op.add_column('subjects', sa.Column('applicable_parallels', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'applicable_parallels')
    # ### end Alembic commands ###
