"""add_user_profile_fields_and_curator_relationship

Revision ID: a2c672f37bbf
Revises: f9283a28ea65
Create Date: 2025-09-23 22:35:38.151424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c672f37bbf'
down_revision: Union[str, Sequence[str], None] = 'f9283a28ea65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.alter_column('grades', 'curator_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_grades_curator_id'), 'grades', ['curator_id'], unique=False)
    op.create_foreign_key(None, 'grades', 'users', ['curator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('grades', 'studentcount')
    op.drop_column('grades', 'shanyrak')
    op.drop_index(op.f('idx_scores_actual_gin'), table_name='scores', postgresql_using='gin')
    op.drop_index(op.f('idx_scores_predicted_gin'), table_name='scores', postgresql_using='gin')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('shanyrak', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_column('users', 'shanyrak')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_index(op.f('idx_scores_predicted_gin'), 'scores', ['predicted_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scores_actual_gin'), 'scores', ['actual_scores'], unique=False, postgresql_using='gin')
    op.add_column('grades', sa.Column('shanyrak', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('studentcount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_index(op.f('ix_grades_curator_id'), table_name='grades')
    op.alter_column('grades', 'curator_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('grades', 'curator_id')
    # ### end Alembic commands ###
