"""add_subject_id_to_scores

Revision ID: add_subject_id_to_scores
Revises: add_subjects_table
Create Date: 2025-09-22 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_subject_id_to_scores'
down_revision = 'add_subjects_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scores_subject_id'), 'scores', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'scores', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_index(op.f('ix_scores_subject_id'), table_name='scores')
    op.drop_column('scores', 'subject_id')
    # ### end Alembic commands ###