"""add_enhanced_school_management_tables

Revision ID: f9283a28ea65
Revises: cb25d9d71933
Create Date: 2025-09-23 21:21:42.315421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9283a28ea65'
down_revision: Union[str, Sequence[str], None] = 'cb25d9d71933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_created_at'), 'subjects', ['created_at'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_grade', sa.Integer(), nullable=False),
    sa.Column('max_grade', sa.Integer(), nullable=False),
    sa.Column('class_letters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_is_active'), 'system_settings', ['is_active'], unique=False)
    op.create_table('curator_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curator_grades_created_at'), 'curator_grades', ['created_at'], unique=False)
    op.create_index(op.f('ix_curator_grades_id'), 'curator_grades', ['id'], unique=False)
    op.create_index('ix_curator_grades_unique', 'curator_grades', ['curator_id', 'grade_id'], unique=True)
    op.create_table('subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroups_created_at'), 'subgroups', ['created_at'], unique=False)
    op.create_index(op.f('ix_subgroups_id'), 'subgroups', ['id'], unique=False)
    op.create_index(op.f('ix_subgroups_is_active'), 'subgroups', ['is_active'], unique=False)
    op.create_index(op.f('ix_subgroups_name'), 'subgroups', ['name'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teacher_assignment_unique', 'teacher_assignments', ['teacher_id', 'subject_id', 'grade_id', 'subgroup_id'], unique=True)
    op.create_index(op.f('ix_teacher_assignments_created_at'), 'teacher_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_id'), 'teacher_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_is_active'), 'teacher_assignments', ['is_active'], unique=False)
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('achievement_date', sa.DateTime(), nullable=False),
    sa.Column('awarded_by', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_achievement_date'), 'achievements', ['achievement_date'], unique=False)
    op.create_index(op.f('ix_achievements_category'), 'achievements', ['category'], unique=False)
    op.create_index(op.f('ix_achievements_created_at'), 'achievements', ['created_at'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_points'), 'achievements', ['points'], unique=False)
    op.create_index(op.f('ix_achievements_title'), 'achievements', ['title'], unique=False)
    op.create_table('disciplinary_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity_level', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('is_resolved', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinary_actions_action_date'), 'disciplinary_actions', ['action_date'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_action_type'), 'disciplinary_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_created_at'), 'disciplinary_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_id'), 'disciplinary_actions', ['id'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_is_resolved'), 'disciplinary_actions', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_severity_level'), 'disciplinary_actions', ['severity_level'], unique=False)
    op.drop_column('grades', 'studentcount')
    op.add_column('scores', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('scores', sa.Column('subgroup_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_scores_actual_gin'), table_name='scores', postgresql_using='gin')
    op.drop_index(op.f('idx_scores_predicted_gin'), table_name='scores', postgresql_using='gin')
    op.create_index(op.f('ix_scores_subject_id'), 'scores', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'scores', 'subgroups', ['subgroup_id'], ['id'])
    op.create_foreign_key(None, 'scores', 'subjects', ['subject_id'], ['id'])
    op.add_column('students', sa.Column('subgroup_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'students', 'subgroups', ['subgroup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    op.drop_column('students', 'subgroup_id')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_index(op.f('ix_scores_subject_id'), table_name='scores')
    op.create_index(op.f('idx_scores_predicted_gin'), 'scores', ['predicted_scores'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_scores_actual_gin'), 'scores', ['actual_scores'], unique=False, postgresql_using='gin')
    op.drop_column('scores', 'subgroup_id')
    op.drop_column('scores', 'subject_id')
    op.add_column('grades', sa.Column('studentcount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_disciplinary_actions_severity_level'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_is_resolved'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_id'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_created_at'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_action_type'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_action_date'), table_name='disciplinary_actions')
    op.drop_table('disciplinary_actions')
    op.drop_index(op.f('ix_achievements_title'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_points'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_created_at'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_category'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_date'), table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_teacher_assignments_is_active'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_created_at'), table_name='teacher_assignments')
    op.drop_index('ix_teacher_assignment_unique', table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_subgroups_name'), table_name='subgroups')
    op.drop_index(op.f('ix_subgroups_is_active'), table_name='subgroups')
    op.drop_index(op.f('ix_subgroups_id'), table_name='subgroups')
    op.drop_index(op.f('ix_subgroups_created_at'), table_name='subgroups')
    op.drop_table('subgroups')
    op.drop_index('ix_curator_grades_unique', table_name='curator_grades')
    op.drop_index(op.f('ix_curator_grades_id'), table_name='curator_grades')
    op.drop_index(op.f('ix_curator_grades_created_at'), table_name='curator_grades')
    op.drop_table('curator_grades')
    op.drop_index(op.f('ix_system_settings_is_active'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_created_at'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
